### ISSUE TITLE
汉化版本1.61（for 3.17.2- LIVE）启动报错0xc0000142问题

### ISSUE THREAD

**Issue by knightwfy** [summerkirakira/starcitizen-localization-cn#2]
启用汉化后，启动游戏，提示0xc0000142错误，并且系统通知Easy ANTI CHEAT unkmown file version (StarCityzen/LIVE/Bin64/dbghelp.dll).关掉汉化后 dbghelp.dll消失游戏能够正常启动

**Comment by summerkirakira** [comment]
这**不是**汉化问题，如果避难所版本在**3.0**以下请**使用星河避难所**启动游戏。请仔细阅读[教程](https://biaoju.site/star-refuge/docs/install-localization)最后部分。
