### ISSUE TITLE
1.17.41避難所問題

### ISSUE THREAD

**Issue by zxc25680373** [summerkirakira/starcitizen-localization-cn#4]
下載本地一直失敗跳出webclient錯誤

**Comment by summerkirakira** [comment]
请检查和GitHub的网络连接是否通畅或使用https://biaoju.site/star-refuge/docs/install-localization 中的离线包

**Comment by zxc25680373** [comment]
我載離線包也會錯誤ㄟ

**Comment by summerkirakira** [comment]
请留下使用离线包错误的截图

**Comment by zxc25680373** [comment]
![image](https://user-images.githubusercontent.com/106025264/203041045-3190babe-305a-416d-a1d9-5c50e57a40c1.png)

**Comment by zxc25680373** [comment]
![image](https://user-images.githubusercontent.com/106025264/203041129-8ffbe88e-a773-4b97-a1b2-67ca10f00bdd.png)

**Comment by zxc25680373** [comment]
大概都是跑到一半就錯誤

**Comment by zxc25680373** [comment]
![image](https://user-images.githubusercontent.com/106025264/203041389-d7e90727-2363-4cdb-8058-45a246d6887b.png)

**Comment by summerkirakira** [comment]
尝试使用其他解压软件

**Comment by summerkirakira** [comment]
看上去好像是系统自带程序的问题

**Comment by zxc25680373** [comment]
![image](https://user-images.githubusercontent.com/106025264/203041766-b231304f-d5b8-486d-a40f-714e304b75b2.png)

**Comment by summerkirakira** [comment]
这不是离线包

**Comment by summerkirakira** [comment]
你应该下载的是https://pan.baidu.com/s/1oqFhJINU_tkgLb__XJSgLg?pwd=kira 这个版本的程序

**Comment by zxc25680373** [comment]
哦原來

**Comment by zxc25680373** [comment]
不過這個好慢

**Comment by zxc25680373** [comment]
所以避難所跳的是我的問題嗎

**Comment by zxc25680373** [comment]
3天都這樣

**Comment by summerkirakira** [comment]
不是很清楚诶，也不排除是语言编码的问题
